name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable Corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build

      - name: Generate SHA256 digest
        run: sha256sum ./dist/* > ./dist/dist.sha256

      - name: Upload build dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Upload SHA256 digest
        uses: actions/upload-artifact@v4
        with:
          name: dist-sha256
          path: ./dist/dist.sha256
