name: Build, Test, Version & Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable Corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm -v

      - run: pnpm install --frozen-lockfile

      - run: pnpm test

      - run: pnpm build

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and push
        id: bump
        run: |
          NEW_VERSION=$(pnpm version patch --no-git-tag-version)
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

          git add package.json pnpm-lock.yaml
          git commit -m "chore: bump version to $NEW_VERSION"

          git push "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD

          if [ "$GITHUB_EVENT_NAME" = "push" ] && [ "$GITHUB_REF" = "refs/heads/main" ]; then
              git tag "$NEW_VERSION"
              git push "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" --tags
          else
              echo "Skipping tag creation: not a push to main branch"
          fi

      - name: Create GitHub release
        if: github.event_name != 'workflow_dispatch'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.new_version }}
          name: Release ${{ env.new_version }}
          draft: false
          prerelease: false

      - name: Setup npm auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public
