name: Build, Test, Version & Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js without pnpm cache
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Enable Corepack & activate pnpm
      - name: Enable Corepack & activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm -v

      # 4️⃣ Install dependencies (cached by lockfile)
      - run: pnpm install --frozen-lockfile

      # 5️⃣ Run tests
      - run: pnpm test

      # 6️⃣ Build package
      - run: pnpm build

      # 7️⃣ Bump version (patch)
      - name: Bump version
        id: version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          NEW_VERSION=$(pnpm version patch -y)
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      # 8️⃣ Push version bump
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push

      # 9️⃣ Publish to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public
