name: Publish

on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Determine version
        id: version
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          echo "Current version in package.json: $CURRENT_VERSION"

          if npm view newtab-js@$CURRENT_VERSION > /dev/null 2>&1; then
            echo "⚠️ Version $CURRENT_VERSION already exists on npm. Auto-bumping..."
            NEW_VERSION=$(pnpm version patch --no-git-tag-version)
            echo "version=$NEW_VERSION" >> $GITHUB_ENV
            echo "bumped=true" >> $GITHUB_ENV
          else
            echo "✅ Version $CURRENT_VERSION is new."
            echo "version=$CURRENT_VERSION" >> $GITHUB_ENV
            echo "bumped=false" >> $GITHUB_ENV
          fi

      - name: Commit version bump
        if: env.bumped == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add package.json pnpm-lock.yaml
          git commit -m "chore: bump version to ${{ env.version }}"
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.version }}
          skip-commit: true
          skip-tag: true

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          name: Release ${{ env.version }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
